webtalk_init -webtalk_dir /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov 1 15:51:52 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "200191280_1777494487_210588423_305" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "jkvbnc0sp03fpj88emefaol6g2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.3_23" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 8.2 (jessie)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2934.421 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1446387617000" -context "sdk\\\\hardware/1446387617000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1446387617000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1446387617000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.3.1" -context "sdk\\\\hardware/1446387617000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1446387617000"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1446387617000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1446387617000"
webtalk_add_data -client sdk -key uid -value "1446387633000" -context "sdk\\\\bsp/1446387633000"
webtalk_add_data -client sdk -key hwid -value "1446387617000" -context "sdk\\\\bsp/1446387633000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1446387633000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1446387633000"
webtalk_add_data -client sdk -key uid -value "1446387636000" -context "sdk\\\\application/1446387636000"
webtalk_add_data -client sdk -key hwid -value "1446387617000" -context "sdk\\\\application/1446387636000"
webtalk_add_data -client sdk -key bspid -value "1446387633000" -context "sdk\\\\application/1446387636000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1446387636000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1446387636000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1446387636000"
webtalk_transmit -clientid 1216175707 -regid "200191280_1777494487_210588423_305" -xml /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
