#
# Vivado (TM) v2014.3.1 (64-bit)
#
# try.tcl: Tcl script for re-creating project 'HW_Design'
#
# Generated by Vivado on Wed Feb 24 16:55:11 CET 2016
# IP Build 1028902 on Fri Sep 26 17:35:13 MDT 2014
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (try.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.bd/system/system.bd"
#    "/home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.bd/system/hdl/system_wrapper.v"
#    "/home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.bd/system/ip/system_ground_0/system_ground_0.upgrade_log"
#    "/home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.upgrade_log"
#    "/home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.bd/system/ip/system_processing_system7_0_axi_periph_2/system_processing_system7_0_axi_periph_2.upgrade_log"
#    "/home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.bd/system/ip/system_NaCl_0_0/system_NaCl_0_0.upgrade_log"
#    "/home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/constrs_1/new/base.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/vivado"]"

# Create project
create_project BASESYSTEM ./vivado

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects BASESYSTEM]
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7z010clg400-1" $obj
set_property "simulator_language" "Mixed" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/nacl_cb/ip_repo"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/bd/system/system.bd"]"\
 "[file normalize "$origin_dir/bd/system/hdl/system_wrapper.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "system_wrapper" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
add_files -fileset constrs_1 -norecurse ./const/base.xdc

