# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.cache/wt [current_project]
set_property parent.project_path /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/ft/Thesis/CryptoCP/CryptoCP_1.0 [current_project]
add_files /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_axi_dma_0_1/system_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_m00_regslice_0/system_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/sources_1/bd/system/hdl/system_wrapper.v
read_xdc /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/constrs_1/new/base.xdc
set_property used_in_implementation false [get_files /home/ft/Thesis/Hardware-Accelerated-SigmaVPN/HW_Design/HW_Design.srcs/constrs_1/new/base.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file system_wrapper.hwdef }
synth_design -top system_wrapper -part xc7z010clg400-1
write_checkpoint system_wrapper.dcp
catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
